services:
  db:
    image: postgres:16-alpine
    container_name: church-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: church_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: church-api
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://user:password@db:5432/church_db?sslmode=disable
      JWT_SECRET: church_secret_key
    depends_on:
      - db

volumes:
  pgdata: